[Proyect]
name = "Disaster_Scraper"
version = "1.0.0"
python_version = "^1.12.4"

[Dependencies]
numpy = "^2.0.1"
pandas = "^2.2.2
bs4 = "^0.0.2"
html5lib= "^1.1"
lxml = "^5.2.2"
requests = "^2.32.3"
googlesearch-python = "^1.2.5"
openai = "^1.39.0"
unidecode = "^1.3.8"